name: lyf_flutter_app
description: "A new Flutter project."
# 下面这一行防止包意外发布到 pub.dev
# 通过使用 `flutter pub publish`。对于私有包，推荐使用这个设置。
publish_to: 'none' # 如果你希望发布到 pub.dev，请删除这一行


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# 依赖项指定你的包运行所需的其他包。
# 要自动升级包依赖到最新版本，可以运行 `flutter pub upgrade --major-versions`。
# 或者，可以通过手动更改以下版本号来更新依赖项到 pub.dev 上可用的最新版本。
# 要查看哪些依赖项有新版本可用，运行 `flutter pub outdated`。
#flutter pub add google_mobile_ads
#flutter pub run build_runner build
#flutter pub run build_runner build --delete-conflicting-outputs
dependencies:
  flutter:
    sdk: flutter


  # 下面为你的应用程序添加了 Cupertino Icons 字体。
  # 在 iOS 风格的图标中使用 CupertinoIcons 类。
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  dio: ^5.6.0
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3
  flutter_inappwebview: ^6.0.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 下面的 "flutter_lints" 包含一组推荐的代码检查，
  # 以鼓励良好的编码实践。该包提供的代码检查集在包的根目录下的
  # `analysis_options.yaml` 文件中被激活。查看该文件了解如何停用特定的代码检查规则
  # 并激活其他规则。
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  retrofit_generator: '>=7.0.0 <8.0.0'


# 有关此文件 Dart 部分的通用信息，请参见：
# https://dart.dev/tools/pub/pubspec

# 下面部分是 Flutter 包特有的内容。
flutter:

  # 下面这一行确保 Material Icons 字体包含在你的应用程序中，
  # 以便你可以在 Material Icons 类中使用图标。
  uses-material-design: true

  # 要向应用程序添加资源，请添加 assets 部分，如下所示：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 一个图像资源可以引用一个或多个分辨率特定的“变体”，参见：
  # https://flutter.dev/assets-and-images/#resolution-aware

  # 有关从包依赖项添加资源的详细信息，请参见：
  # https://flutter.dev/assets-and-images/#from-packages

  # 要向应用程序添加自定义字体，请在此处的 "flutter" 部分中添加 fonts 部分。
  # 该列表中的每个条目应有一个“family”键，指定字体系列名称，
  # 以及一个“fonts”键，包含字体资源及其描述符的列表。
  # 例如：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关从包依赖项中使用字体的详细信息，请参见：
  # https://flutter.dev/custom-fonts/#from-packages
